### ISSUE TITLE
Objects dropped in mid air stays in mid air 

### ISSUE THREAD

**Issue by 0viken0** [rt-2/SA-ARP#5]
sometimes when a objects is dropped in mid air it get stuck in mid air

**Comment by rt-2** [comment]
It is always the case, we in the code do not knows where the floors are, and even with MapAndreas, we only have 1 floor per coordinates in all world. Meaning that there is no way to know where are the floors inside any buildings, in dual level highways and in any other area where there could be 2 floors for the same coords.
The objects stays exactly where they are dropped but should in theory be always accessible since someone had to drop it there.
FOR NOW (and probably always):
Role-Play as if the object was on the floor near below.
P.S. I hope I understand the issue well, if not correct me.
