### ISSUE TITLE
Refueling the train while moving

### ISSUE THREAD

**Issue by 0viken0** [rt-2/sa-arp#6]
there is a way to refuel the train while moving

**Comment by rt-2** [comment]
Normally, once you get out of range, the refuel should stop?

**Comment by 0viken0** [comment]
no, i was moving and moving and refuel did not stop until i turned on teh engine

**Comment by rt-2** [comment]
Right now there is a bug in one of the function about refueling, once we clear that error, we should test this issue again because this is now supposed to happen, but it might be caused by this other internal problem that I intend to fix today/tomorrow.
I will keep you updated, I will post again on this thread when it should be worthy to test again.
Thank you!

**Comment by rt-2** [comment]
We added a test in the /refuel cmd to check if the player's vehicle is stopped before refueling.
That should do it.

**Comment by rt-2** [comment]
Did not have time to restart, will update here when server will be restarted

**Comment by rt-2** [comment]
I am restarting the server at the moment, it would be worthy to test now.

**Comment by rt-2** [comment]
Tested ingame by @0viken0 and works now.

**Comment by 0viken0** [comment]
bug is fixed

**Comment by rt-2** [comment]
Tested in-game by @0viken0  and works now.
